name: Clojure CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Compile test code
      run: lein cljsbuild once test
    - name: Serve the content
      run: python -m SimpleHTTPServer 3449 &
    - name: Install Puppeteer
      run: npm i puppeteer
    - name: Wait for server
      run: sleep 10s
    - name: Run tests
      run: node puppeteer-runner.js
