name: Clojure CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
    - name: Compile test code
      run: lein cljsbuild once test
    - name: Serve the content
      working-directory: ./resources/public
      run: python -m SimpleHTTPServer 3449 &
    - name: Install Puppeteer
      run: npm i puppeteer
    - name: Wait for server
      run: sleep 10s
    - name: Run tests
      run: node puppeteer-runner.js

  build-api-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Build API documentation
      run: lein codox

  build-human-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Build Human Readable documentation
      run: lein run
