name: Clojure CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
    - name: Compile test code
      run: lein cljsbuild once test
    - name: Serve the content
      working-directory: ./resources/public
      run: python -m SimpleHTTPServer 3449 &
    - name: Install Puppeteer
      run: npm i puppeteer
    - name: Wait for server
      run: sleep 10s
    - name: Run tests
      run: node puppeteer-runner.js
      
  is-master:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    on:
      push:
        # Sequence of patterns matched against refs/heads
        branches:    
          - master         # Push events on master branch
    steps:
    - name: Echo Master
      run: echo "This is Master"

  build-codox:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: is-master
    steps:
    - uses: actions/checkout@v1
    - name: Build Codox
      run: lein codox
