name: Master on Push

on:
  push:
    branches:    
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
    - name: Compile test code
      run: lein cljsbuild once test
    - name: Serve the content
      working-directory: ./resources/public
      run: python -m SimpleHTTPServer 3449 &
    - name: Install Puppeteer
      run: npm i puppeteer
    - name: Wait for server
      run: sleep 10s
    - name: Run tests
      run: node puppeteer-runner.js

  build-codox:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Build Codox
      run: lein codox

  build-documentation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: Build documentation
      run: lein run
    - name: Convert documentation to public url
      run: sed -i 's/http:\/\/localhost:8000\/src/https:\/\/raw.githubusercontent.com\/samedhi\/firemore\/master\/src/g' public/firemore-docs/posts-output/2019-06-26-README/index.html
